baseURL = "/"
languageCode = "en-us"
title = "Your Project Documentation"

# Basic configuration
enableGitInfo = true
enableRobotsTXT = true
defaultContentLanguage = "en"

# Site parameters
[params]
description = "Comprehensive documentation for your project"
author = "Your Name"
version = "1.0.0"
logo = "/images/logo.svg"
footer = "© 2024 Your Project. Built with Hugo."

# Social media links
github = "https://github.com/yourusername/project"
twitter = "https://twitter.com/yourusername"

# Markup configuration
[markup.highlight]
style = "dracula"
lineNos = true

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[build]
  writeStats = true  # If you're using Hugo Pipes

[minify]
  minifyOutput = true  # Optional, for production


# Menu configuration
[menu]
[[menu.docs]]
name = "Home"
url = "/docs"
weight = 10

[[menu.docs]]
name = "Getting Started"
url = "/docs/getting-started/"
weight = 20

[[menu.docs]]
name = "Installation"
url = "/docs/installation/"
weight = 30

[[menu.docs]]
name = "API Reference"
url = "/docs/api/"
weight = 40

# Output formats
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]

# Privacy settings
[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
disable = true
[privacy.twitter]
disable = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = true

# Security headers
[server]
[[server.headers]]
for = "/**"
[server.headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data:;"
